### ISSUE TITLE
Entity Issue 1.11.0

### ISSUE THREAD

**Issue by CosmicjLightning** [ooibc88/blockbench#15]
So when i was creating an entity and lets say i wanted to use the waterflow image for one of the pieces, it auto applied it to all 3 cubes even when clicked on the one cube and no scroll bar to go choose width, or etc. So I closed and reload the program, now with nothing clicked when I import the textures, it replaces one texture instead of adding it. I'm going to downgrade but it would be nice for it to not replace textures.

If you close this with no info or to why like last time you guarentee you dont want users to use your program anymore. You used to be nice, show if i did something wrong, now you close an issue that is still prominent in your program with no aid, and your website doesnt let us download 1.9.1, so in other words please fix this or explain what Im doing wrong instead of closing with no help at all, its rude and mean and certifies i'll go use your competitors program which i dont want to do.

**Comment by JannisX11** [comment]
Is appears to be that this repository contains a framework to analyze private blockchains which stands in no relation to entities and textures.
