### ISSUE TITLE
Help in running benchmark for quorum_vote

### ISSUE THREAD

**Issue by xiaohua0921** [ooibc88/blockbench#17]
When I run start-miner.sh , the error message is "flag provided but not defined: -voteaccout " in log file.

the problem command is " geth --datadir=~/chain-data-quorum_vote --rpccorsdomain "*" --nodiscover --voteaccout "0xeb6902c98ed64b7b16f743a7c09b36b8fa1aff59" --votepassword "" --rpc --rpcaddr 0.0.0.0 --rpcport 8000 "

**Comment by ug93tad** [comment]
@bulldosers can you help?

**Comment by xiaohua0921** [comment]
I modified the genesis_quorum.json file.Move the “alloc” part to the front .
{
  "alloc": { 
    "0xeb6902c98ed64b7b16f743a7c09b36b8fa1aff59": { 
      "balance": "1000000000000000000000000000" 
    }, 
    "0x981010def42136f95ad6f302052e660bac5f2b3f": { 
      "balance": "1000000000000000000000000000" 
    }, 
    "0xbe80f950c3d6c6baecd78b2d32a65275bad9ab58": { 
      "balance": "1000000000000000000000000000" 
    }, 
    "0x748d769bdecf1d4ad0b0311af3165acf6eb0f44f": { 
      "balance": "1000000000000000000000000000" 
    }, 
    "0x8f720812bec35d562e01b19b3e34706e14ebbcbb": { 
      "balance": "1000000000000000000000000000" 
    }, 
    "0x6f313ba59ca1d26d5493ce49174c1db8f32bcc62": { 
      "balance": "1000000000000000000000000000" 
    }, 
      "storage": { 
        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x01",  
        "0xe6f536d27a521b28872c68cca12166427f8b743cdd94329210f3576e907445cb": "0x01",
        "0xa94aef72deeadef2674d21b5bc9be89c2355ee0138bb9174c1abef1c9e97cb39": "0x01",
        "0xe836c6b82bb3e87704e790c6a7d41c55f5890a68deaf2f175608676e278abf7c": "0x01",
        "0xa7f711c3f9ea02f5df41d056c2cfe86c8f5b3154a71a8702d0731a3b332b7d68": "0x01",
        "0xe9c15c0ce982fc5ad0d6fe403e052023f852579742727e35bd32b12aabb1a713": "0x01",
        "0xd7986a4db5f1b81b35f2f1e406fc4b76a6012050440747da3ac7f14e951c38b0": "0x01",
        "0xc45ab9ad0cac40685131b0af4d6049bf7572838814a41c011c0b46e559b50cb4": "0x01",
        "0x0000000000000000000000000000000000000000000000000000000000000004": "0x01",
        "0x512bd3dc1856e4830f731bfca16627ef1b2b89ba0e2d20cc0c623a82dbe4e6c1": "0x01"    
       }
    },
    "coinbase": "0x3333333333333333333333333333333333333333",
    "config": {
      "homesteadBlock": 0
    },
    "difficulty": "0x00",
    "extraData": "0x00",
    "gasLimit": "0xFFEFD800",
    "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
    "nonce": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "timestamp": "0x00"
}
