### ISSUE TITLE
help in deploy smart-contract

### ISSUE THREAD

**Issue by xiaohua0921** [ooibc88/blockbench#22]
When I run the parity and ethereum , I meet the error “ driver: evm_utils.cc:334: std::__cxx11::string BBUtils::EVMUtils::lookup_smart_contract_address_or_die(const string&, const string&): Assertion `r.find(""result":null") == std::string::npos' failed. " . I found the reason is the code " assert(r.find("\"result\":null") == std::string::npos); " in function 
"lookup_smart_contract_address_or_die" , I have print r，the information is " {"jsonrpc":"2.0","result":null,"id":1} " , but in parity ，the line of code is annotated ，so there haven't this error , so I want to know , whether is correct or not of the r .

**Comment by ug93tad** [comment]
This error means that the smart contract was not deployed successfully.

**Comment by ug93tad** [comment]
both Ethereum and Parity use the same DB, there shouldn't be any differences in evm_utils.cc

**Comment by xiaohua0921** [comment]
I have checked the code , there was no differences in between Eth and parity .But I print the return information of "lookup_smart_contract_address_or_die" still is “{"jsonrpc":"2.0","result":null,"id":1} ” ，I do not know what may be the reason . And I found the "from_address" is different between eth and parity .

**Comment by ug93tad** [comment]
The reason is that the smart contract failed to deploy. Can you post your server log?

**Comment by xiaohua0921** [comment]
The eth_log and client_log as follow:
[eth_log.txt](https://github.com/ooibc88/blockbench/files/1982216/eth_log.txt)

[client_192.168.0.128_16.txt](https://github.com/ooibc88/blockbench/files/1982217/client_192.168.0.128_16.txt)

**Comment by ug93tad** [comment]
from the log, it looks like the contract was submitted, but it hasn't been included in a block yet. 

try to increase deploy wait time, e.g. specifying "-wt 120" or higher value, in the start-clients.sh

**Comment by keruisiya** [comment]
@xiaohua0921 
hello,I am currently experiencing this problem as you said:
` driver: evm_utils.cc:334: std::__cxx11::string BBUtils::EVMUtils::lookup_smart_contract_address_or_die(const string&, const string&): Assertion `r.find(""result":null") == std::string::npos' failed. " . I found the reason is the code " assert(r.find(""result":null") == std::string::npos); `
 How did you solve it at the time?  thank you！
