### ISSUE TITLE
help in the value of endpoint:   192.168.0.128:8000/chaincode

### ISSUE THREAD

**Issue by xiaohua0921** [ooibc88/blockbench#23]
when I print the value of endpoint , in parity,the value is 192.168.0.128:8000 , but in ethereum , the value is 
 192.168.0.128:8000/chaincode , caused an error in the function "lookup_smart_contract_address_or_die" . Should I modify the value of endpoint ???

**Comment by ug93tad** [comment]
this should not be the case. The start-clients.sh for Ethereum specifies $host:8000 as the endpoint. 

did you modify the start-clients.sh or any other files?

**Comment by xiaohua0921** [comment]
Thank you very much ! I found I specified $host:8080/chaincode as the endpoint in start-clients.sh .
