### ISSUE TITLE
help in run hyperledger

### ISSUE THREAD

**Issue by xiaohua0921** [ooibc88/blockbench#24]
I found the EXE_HOME only is ".../src/macro/kvstore" and haven't  such as "$ETH_HOME/../src/smallbank/ycsb" when I want start_client by smallbank . The directory of ".../src/macro/smallbank" don't have ycsb folder .  I want to know hyperledger whether achieves smallbank or not ?

**Comment by ug93tad** [comment]
smallbank isn't ycsb. 
you can set EXE_HOME to "../src/macro/smallbank"
also need to specify "-db hyperledger" In the start-clients.sh (see  the latest version)
