### ISSUE TITLE
help in  change the from_address_

### ISSUE THREAD

**Issue by xiaohua0921** [ooibc88/blockbench#25]
when I print all txs , I found the value of "from" always is "0x0956e52cb729097e58fc3d945b0464e0ad68df2e" , I found the adress in config.toml.template . If all transactions are initiated by the same account, I think maybe it is wrong . And I query all accounts by call the  api “eth_accounts” ,  it returns 32 accounts , but when I query their balance by call the api " eth_getBalance " ,  I found the value is "0x0" of all accounts . I don't know how to make all accounts have the opportunity to send transactions  and has some balance ???

**Comment by ug93tad** [comment]
currently, the client will pick the first account from the list to send. 
if you want to select a different account, you can modify the get_from_address(.) method in core/evm_utils.cc

there is no currency exchanged between account, so there're no balance.
