### ISSUE TITLE
help in run function poll_txs_by_block_number 

### ISSUE THREAD

**Issue by xiaohua0921** [ooibc88/blockbench#26]
When I  look over the function  poll_txs_by_block_number and poll_txs_by_block_hash ，I think that the return value of these two functions should be the same . But actually , in the code of " std::vector<std::string> ret = get_list_field(r, "transactions"); "  , it can't get the transcation list , because  in  the  function of get_list_field ,the string is split by ','  .   I look over the return value of  "eth_getBlockByNumber" API , the return transactions are split by ' } ' . I don't know if my conclusion is correct .

Another question in the code of 
 "
inline std::vector<std::string> poll_txs_by_block_number(const std::string &endpoint, int block_number) {
  std::string request = GET_BLOCK_BY_NUMBER_PREFIX +   std::to_string(block_number) +
                        GET_BLOCK_BY_NUMBER_SUFFIX;
  auto r = send_jsonrpc_request(endpoint, REQUEST_HEADERS, request);
  std::vector<std::string> ret = get_list_field(r, "transactions");
  std::vector<std::string> uncles = get_list_field(r, "uncles");
  for (std::string uncle : uncles) {
    std::vector<std::string> uncletxs = poll_txs_by_block_hash(endpoint, uncle);
    for (std::string tx : uncletxs) ret.push_back(tx);
  }
  return ret;
"
I can't understanding why do we need to add the return tx of function "poll_txs_by_block_hash" to the result ret of "get_list_field(r, "transactions") " , I think this will lead to repeated transcation in the vector .

**Comment by ug93tad** [comment]
you could try to use 'curl' on a running Ethereum server and observe the exact outputs.
