### ISSUE TITLE
How do I setup blockbench for Quorum private chain analysis

### ISSUE THREAD

**Issue by sivachaitanya** [ooibc88/blockbench#3]
I have a Quorum private chain of 4 nodes spread across aws and azure instances. Can you please give me a brief overview of the setup I have to do for blockbench in this regards ?

Cheers
S

**Comment by bulldosers** [comment]
The Quorum is based on Ethereum, so the usage of Quorum on BlockBench is very similar with the usage of Ethereum. We've create a temporary branch (quorum) for the early-release supporting Quorum. The documentations are at benchmark/quorum-XXX directory

There are two alternative consensus mechanisms in Quorum, one called QuorumChain(a voting method), the other is Raft-based consensus. For the two consensus mechanisms, you can refer to the bash script `run-bench.sh` in [quorum-raft](https://github.com/ooibc88/blockbench/tree/quorum/benchmark/quorum_raft) for Raft and [quorum-vote](https://github.com/ooibc88/blockbench/tree/quorum/benchmark/quorum_vote) for QuorumChain.

**Comment by sivachaitanya** [comment]
Thanks for the reply @bulldosers  So I need to paste the branch contents on each of running nodes across AWS , Azure and start them separately or have to run them all instructions on one node independently ?

**Comment by bulldosers** [comment]
Sorry, I am not familiar with AWS,Azure. We run the script at only one NFS-mounted directory in cluster and use the `run-bench.sh` script to start all nodes separately.

**Comment by sivachaitanya** [comment]
I have 1 node on azure and 1 node on AWS, boot node and blockmaker is on Azure and voter is on AWS. Can you please let me know which files I need to edit? and also for running run-bench.sh I dont need to deploy the smart contracts on the either node right ?

**Comment by bulldosers** [comment]
If you want to directly use the script `run-bench.sh`, there are three setps that you may need to do. 
First, you need to edit the `env.sh` to change the environment variable;
Second, you may need to edit the `hosts` and `clients` file to set it as your own node address(Maybe ip for AWS or Azure, I am not sure);
Third, the first serve is blockmaker and others are votes by default and you can change it by editing the `start-mining` file.

If you have deployed your Quorum network manually, you can use the `driver` at [kvstore](https://github.com/ooibc88/blockbench/tree/master/src/macro/kvstore) for ycsb and [smallbank](https://github.com/ooibc88/blockbench/tree/master/src/macro/smallbank) for smallbank. 
By the way, you can get more details about the `driver` from [README.md](https://github.com/ooibc88/blockbench/tree/master/src/macro)

About the deploying of the smart contracts, we have integrated the deploying procedure into our `driver`, thus you don't need to do it by yourself.

I hope my explanation can help you, there may be some differences between AWS and cluster.

**Comment by lulinglingcufe** [comment]
Appreciatey your work , both paper and code!  👍 : ）
