### ISSUE TITLE
help in run ethereum with smallbank

### ISSUE THREAD

**Issue by xiaohua0921** [ooibc88/blockbench#31]
when it call the function "lookup_smart_contract_address_or_die" , it  always  return {"jsonrpc":"2.0","id":1,"result":null} , and at the last step , the value of receipt is not null , I print the value is "receipt: 0xad1deef543e1ced521bac1ffa1d4af629a1c32d3c34fc204fb0f58d513f5bcbf " ,  but when I run parity , it can successfully get the value of contractAddress by call the function "lookup_smart_contract_address_or_die" .

**Comment by xiaohua0921** [comment]
I found the reason for the above error is that mining is very very very slow. but I never modified the CustomGenesis_8.json file . In my experience , the cost time of first mining is 30 minutes ， and when run start client ，the miner status wasn‘t change . I have set the sleep time to 2000 in start-multi-client.sh and run-bench.sh . I run blockbench upon the virtual machines with 2 cores and 20G memory， maybe the reason is insufficient computing power . Could you tell me why the speed of mining is so slow ? I have test the mining time in independent ethereum private chain ,it was also very slow.

**Comment by ug93tad** [comment]
you could make the PoW difficulty lower, by setting it in the CustomGenesis_*.json file
