### ISSUE TITLE
How to build ./driver binary?

### ISSUE THREAD

**Issue by phucnguyenit** [ooibc88/blockbench#34]
**`blockbench/benchmark/ethereum/start-clients.sh`** 
In the code line: 

**nohup ./driver -db ethereum -threads $1 -P workloads/workloada.spec -endpoint $host:8000 -txrate $4 -wt 60 > $LOG_DIR/client_$host"_"$1 2>&1 &**

 So how to build `./driver` binary?  Also go to **blockbench/src/macro/kvstore** then make command but this raise the issue: 

core/hyperledger_utils.o: In function `BBUtils::HLUtils::get_tip_block_number(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/opt/blockbench/src/macro/kvstore/core/hyperledger_utils.cc:143: undefined reference to `RestClient::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
core/hyperledger_utils.o: In function `BBUtils::HLUtils::poll_txs_by_block_number(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/opt/blockbench/src/macro/kvstore/core/hyperledger_utils.cc:164: undefined reference to `RestClient::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
core/hyperledger_utils.o: In function `BBUtils::send_jsonrpc_request(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/opt/blockbench/src/macro/kvstore/core/bb_utils.h:93: undefined reference to `RestClient::post(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status

So how to deal with that? 

Thanks

**Comment by phucnguyenit** [comment]
Thanks @herrBez . Got that by install restclient.cpp and libcurl to compile driver

**Comment by herrBez** [comment]
Did you succeed with the configuration of blockbench? (I'm stuck :/)

**Comment by phucnguyenit** [comment]
@herrBez : Which problem did you see in your configuration? Let me know, hope to help you quickly..

**Comment by starrycheng** [comment]
@herrBez I am wondering what is the concrete command line to for the compilation and execution of driver the restclient-cpp library.

**Comment by starrycheng** [comment]
Hi! @herrBez May I ask what is the concrete command line of the compilation and execution of driver the restclient-cpp library to build the ./driver binary? Thank you!

**Comment by herrBez** [comment]
Hi, I'm not sure about what you ask (and I'm not sure if with the following procedure you will install more things than needed. After all I'm not the developer of this repo)

I report instruction for Ubuntu/Linux not Windows nor Mac:

You need essentially the `libcurl` library with the headers and `restclient-cpp` with both headers and binary. For the former you can try with the following command: 


       sudo apt-get install libcurl4-openssl-dev

While for the latter. You need to download the latest release of rest-client https://github.com/mrtazz/restclient-cpp/archive/0.4.4.zip, unzip it and follow the instructions of the README:
       

      ./autogen.sh 
      ./configure
      make install

Now you have to go in the directory with the driver source code and execute make. Et voilà you have the binary.

**Comment by starrycheng** [comment]
@herrBez Hi, thank you for your suggestion. My system is Mac OS and I believe I have install the libcurl and res-client successfully according to the install instructions customized for Mac. when I go to the directory of /blockbench/src/macro/kvstore(which is one of the driver source code directory?) when I execute `make`, I encounter the following errors:
```
bogon:kvstore starry$ make                                                                            │bogon:macro starry$ kvscore  -db parity -threads 1 -P workloads/workloada.spec -txrate 5 -endpoint lo
/Library/Developer/CommandLineTools/usr/bin/make -C core                                              │calhost:8545 -wl ycsb -wt 20
make[1]: Nothing to be done for `all'.                                                                │-bash: kvscore: command not found
/Library/Developer/CommandLineTools/usr/bin/make -C db                                                │bogon:macro starry$ kvstore  -db parity -threads 1 -P workloads/workloada.spec -txrate 5 -endpoint lo
g++ -std=c++11 -c -g -Wall -fgnu-tm -I../ db_factory.cc -o db_factory.o                               │calhost:8545 -wl ycsb -wt 20
clang: error: unknown argument: '-fgnu-tm'                                                            │-bash: kvstore: command not found
make[1]: *** [db_factory.o] Error 1                                                                   │bogon:macro starry$ make
make: *** [db] Error 2
``` 
Is the error related to gcc compiler? Or is the error that is caused by mistakenly intalled res-client and libcurl?

**Comment by bigboss88** [comment]
@starrycheng 
Hi it seems that the gcc command that is not known is -fgnu-tm which is

> When the option -fgnu-tm is specified, the compiler generates code for the Linux variant of Intel’s current Transactional Memory ABI specification document (Revision 1.1, May 6 2009)

Since you're using Mac OS this could be a problem
