### ISSUE TITLE
Hyperledger Analytic Q2 Question 

### ISSUE THREAD

**Issue by bigboss88** [ooibc88/blockbench#38]
Hi

In your hyperledger analytic contract Q2 doesn't seem to do what you say it does.

The Q2 is defined as
> Compute the largest transaction value involving a given account between block i and block j.

However in Your `bench_q2.js` the method that you call is QueryAccount however this only returns the balance at a certain block. It doesn't look through blocks i to j and it doesn't return the max transaction value

RangeAccount still just returns a balance 

In your paper the code you provided was 

![image](https://user-images.githubusercontent.com/22649957/41660326-22e3e8c2-7472-11e8-8c71-a1a6975a1d49.png)

I'm just wondering where and how to implement Q2

**Comment by ug93tad** [comment]
the code in the paper is for Hyperledger. it is written in Go. 

For Ethereum, the bench_q2.js is correct.

**Comment by bigboss88** [comment]
Hi @ug93tad 

I was talking about the hyperledger versions of the benchmark 

Specifically I was talking about how bench_q2.js calls the QueryAccount function in the go code

![image](https://user-images.githubusercontent.com/22649957/41717912-aec73ff0-7531-11e8-8102-4754b028d323.png)

And here is that function in the go code

![image](https://user-images.githubusercontent.com/22649957/41717936-cecf844c-7531-11e8-9d93-d2f62c3c98aa.png)

 query account only takes in the account and a block number. Then it returns the account balance at that block

It doesn't seem to actually find the Max Transaction value of an account between blocks i and j. It just gets the balance of an account at block i

**Comment by ug93tad** [comment]
oh i see. There're a mix-up in the implementation of bench_q1.js and bench_q2.js here. 

The idea is to use query_account for every block from start_block to end_block, similar to the "get_max" function in bench_q1.js. (In fact, bench_q1.js was supposed to contain the correct implementation for Q2, and vice-versa). 

We'll update the code. 
@ijingo

**Comment by ijingo** [comment]
@ug93tad  not a mix-up, it seems a typo.

There is a "range_account" method in [analytic.go](https://github.com/ooibc88/blockbench/blob/master/benchmark/contracts/hyperledger/go/analytic/analytic.go#L347) for this query, which takes in three parameters.

Change the "QueryAccount" (line 18) in [bench_q2.js](https://github.com/ooibc88/blockbench/blob/master/src/micro/analytic/hyperledger/bench_q2.js#L18) to "RangeAccount" to invoke the correct query.

**Comment by ijingo** [comment]
@bigboss88 

Hi, it seems to me the query works.  I am not so sure about "return the max balance of the account which is different than the max transaction value" you said. 

According to the implementation, the loop will start from the latest version of one account (lines 367 - 370) and stop until the block number is smaller than the input range (line 377), so no matter what end block you input, it will scan start from the latest one. Try some different start block number as the input, it may output different loop numbers.

**Comment by bigboss88** [comment]
@ijingo 
Ok that makes sense 

What I meant was that Q2 is supposed to find the max transaction value of an account between block i and j

Unless I'm wrong in the go code it's comparing the balance of the account versions 

if balance.Val > ret && balance.StartBlock >= start_blk && balance.StartBlock <= end_blk {
			ret = balance.Val
		}

**Comment by ijingo** [comment]
@bigboss88 

Oh yes, you are right, this one should be Q3 like q3 in [ethereum analytics](https://github.com/ooibc88/blockbench/tree/master/src/micro/analytic/ethereum#run)

**Comment by bigboss88** [comment]
@ijingo 
Ok thanks I'll make those changes
