### ISSUE TITLE
help in running benchmark/ethereum ssh timed out problem

### ISSUE THREAD

**Issue by starrycheng** [ooibc88/blockbench#39]
@ijingo  @ug93tad  @dloghin  there are some configurations set in file `/benchmark/ethereum/hosts` and `benchmark/ethereum/clients`, 
when I run 
`./run-bench.sh 4 32 4 8`
I always encounter the following output and I am not sure if it is an error which will prohibit the generation of the final results
`ssh: connect to host 10.0.0.100 port 22: Operation timed out
done node 10.0.0.100`

I am wondering if I need to modify the contents in `/benchmark/ethereum/hosts` and `/benchmark/ethereum/clients` to fit the conditions of my own computer? If every user needs to modify them, then according to what guidance should we modify?

**Comment by dloghin** [comment]
Hi,

The IP addresses in `hosts` and `clients` must match your cluster's configuration. For your error 
`ssh: connect to host 10.0.0.100 port 22: Operation timed out done node 10.0.0.100`, please check that node 10.0.0.100 is up and ssh is working. Also, make sure you set password-less ssh access among nodes in your cluster.

For the second part of your question, `hosts` contains the IP addresses of nodes that act as miners and `clients` contains IP addresses of nodes that generate transactions.

**Comment by starrycheng** [comment]
@dloghin  Hi, I run the codes on my own computer instead of a cluster. I am wondering that the command line `./run-bench.sh 4 32 4 8` only satisfies the situation with a cluster. Do you have any ideas how to run the codes on a local computer instead of a cluster?

**Comment by dloghin** [comment]
@starrycheng - On I single node, I suggest to start by running the micro-benchmarks in `src/micro/`. For this, firstly make sure you install hyperledger and then start hyperledger peer on you system. You can use the `start-root.sh` script in `benchmark/hyperledger` to start peer. Also, make sure the settings in `benchmark/hyperledger/env.sh` are valid for your system.

If you want to see the output of hyperledger in the terminal and better control the process, edit `start-root.sh` by removing the nohup and the redirection to log file on the last line. In other words, the last line should look like: `$HL_SOURCE/build/bin/peer node start`

Once peer is running (you can check with `ps aux | grep peer`), go to the benchmarks in `src/micro`. For example, go to `src/micro/cpuheavy/hyperledger` and run:
```
node deploy.js
node invoke.js 1000000
```
You should see some messages in the hyperledger terminal where you have issued the `start-root.sh`

**Comment by ballexaa** [comment]
@dloghin i think the installation of blockbench and hyperledger was ok. 

However i wanted to check that everything is fine before cloning the VM and i ran 
blockbench-master/src/micro/cpuheavy/hyperledger$ node deploy.js 
{"jsonrpc":"2.0","method":"deploy","params":{"type":1,"chaincodeID":{"path":"https://github.com/ijingo/chaincode-test/sorter"},"ctorMsg":{"args":["init"]}},"id":1}
problem with request: connect ECONNREFUSED 127.0.0.1:7050

i"m not sure what"s supposed to be running on port 7050 and how can i start that.
Any idea?

Also, is there any way to generate graphics on the test results?

**Comment by dloghin** [comment]
@ballexaa - Make sure you start `peer` on your VM. You can use `start-root.sh` to start peer on one VM. If peer is started, you should see it in ps:
```
ps aux | grep peer
```
and also it should be listening on 7050, 7051 and 7053
```
sudo netstat -tlnp
```
should result in something like:
```
tcp6       0      0 :::7050                 :::*                    LISTEN      2249/peer       
tcp6       0      0 :::7051                 :::*                    LISTEN      2249/peer       
tcp6       0      0 :::7053                 :::*                    LISTEN      2249/peer   
```

**Comment by ballexaa** [comment]
@dloghin i did all that and as i see in the star-root.sh there is just one line about what should start 
export CORE_VM_ENDPOINT=http://localhost:2375 

and i do get this process with port 2375 started, but the others that you mentioned 7050, 7051 and 7053...i don't know where do they come from, or what they are. Clearly something is missing from the installation  procedure

**Comment by ballexaa** [comment]
also by starting peer i get the following and i didn"t configure anywhere this directory data/dinhtta/hyperledger/production/db

a@master:/opt/gopath/src/github.com/hyperledger/fabric$ peer node start
20:01:37.955 [eventhub_producer] start -> INFO 001 event processor started
20:01:37.956 [nodeCmd] serve -> INFO 002 Security enabled status: false
20:01:37.956 [nodeCmd] serve -> INFO 003 Privacy enabled status: false
panic: Error making directory path [/data/dinhtta/hyperledger/production/db]: mkdir /data: permission denied

goroutine 1 [running]:
github.com/hyperledger/fabric/core/db.(*OpenchainDB).open(0xc4201e6e70)
	/opt/gopath/src/github.com/hyperledger/fabric/core/db/db.go:161 +0xb5a
github.com/hyperledger/fabric/core/db.Start()
	/opt/gopath/src/github.com/hyperledger/fabric/core/db/db.go:77 +0x2d
github.com/hyperledger/fabric/peer/node.serve(0x12afbb8, 0x0, 0x0, 0x0, 0x4)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/node/start.go:123 +0x3dc
github.com/hyperledger/fabric/peer/node.glob..func1(0x1255c00, 0x12afbb8, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/node/start.go:67 +0x3f
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute(0x1255c00, 0x12afbb8, 0x0, 0x0, 0x1255c00, 0x12afbb8)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:599 +0x3db
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1256480, 0x12911d0, 0xf, 0xc420255190)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute(0x1256480, 0x0, 0xffffffffffffffff)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/peer/main.go:122 +0x5c3
a@master:/opt/gopath/src/github.com/hyperledger/fabric$

**Comment by dloghin** [comment]
@ballexaa - It seems to be an issue with our configuration. We will try to make it easier to setup.

Meanwhile, you can edit `benchmark/hyperledger/hl_core.yaml`. At line 215, change `fileSystemPath: /data/dinhtta/hyperledger/production` to a path accessible to your user. You can just set it to `hyperledger/production` such that when you start peer from `benchmark/hyperledger/`, it will create a folder `hyperledger/production`.

**Comment by starrycheng** [comment]
@dloghin Hi, when I run `node deploy.js` I got an error as `{"jsonrpc":"2.0","method":"deploy","params":{"type":1,"chaincodeID":{"path":"https://github.com/ijingo/chaincode-test/sorter"},"ctorMsg":{"args":["init"]}},"id":1}
problem with request: Parse Error` and do you know how to fix it? Thank you!

**Comment by dloghin** [comment]
@starrycheng No, that output shows the grep process itself. It means that peer has not stated. Can you post the output of `start-root.sh` or of the script you are using to start `peer`?

**Comment by starrycheng** [comment]
@dloghin  My `start-root.sh` is as follows:
```
#!/bin/bash

cd `dirname ${BASH_SOURCE-$0}`
. env.sh

export CORE_PEER_ID=vp0
export CORE_PEER_ADDRESSAUTODETECT=true
export CORE_PEER_NETWORKID=dev2
export CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
export CORE_PEER_FILE_SYSTEM_PATH=$HL_DATA/hyperledger
export CORE_VM_ENDPOINT=http://localhost:2375
export CORE_PBFT_GENERAL_MODE=batch

rm -rf $CORE_PEER_FILE_SYSTEM_PATH
mkdir -p $CORE_PEER_FILE_SYSTEM_PATH
cd $HL_SOURCE/peer node start > hl_log
```
And I found that there is not any `js` file under the directory of `/Users/starry/src/github.com/hyperledger/fabric/peer`.
Instead, there is a folder named `node` which contain `start.go` file. Thus I suspect that `node start` is not effective. And maybe `go run start.go` would serve. 
However, when I change the `start-root.sh` to 
```
#!/bin/bash

cd `dirname ${BASH_SOURCE-$0}`
. env.sh

export CORE_PEER_ID=vp0
export CORE_PEER_ADDRESSAUTODETECT=true
export CORE_PEER_NETWORKID=dev2
export CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
export CORE_PEER_FILE_SYSTEM_PATH=$HL_DATA/hyperledger
export CORE_VM_ENDPOINT=http://localhost:2375
export CORE_PBFT_GENERAL_MODE=batch

rm -rf $CORE_PEER_FILE_SYSTEM_PATH
mkdir -p $CORE_PEER_FILE_SYSTEM_PATH
$HL_SOURCE/peer/node go run start.go > hl_log
```
I encountered an error saying that 
`-bash: /Users/starry/src/github.com/hyperledger/fabric/peer/node: is a directory`

When I change the `start-root.sh` file to 
```
#!/bin/bash

cd `dirname ${BASH_SOURCE-$0}`
. env.sh

export CORE_PEER_ID=vp0
export CORE_PEER_ADDRESSAUTODETECT=true
export CORE_PEER_NETWORKID=dev2
export CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
export CORE_PEER_FILE_SYSTEM_PATH=$HL_DATA/hyperledger
export CORE_VM_ENDPOINT=http://localhost:2375
export CORE_PBFT_GENERAL_MODE=batch

rm -rf $CORE_PEER_FILE_SYSTEM_PATH
mkdir -p $CORE_PEER_FILE_SYSTEM_PATH
cd $HL_SOURCE/peer/node
go run start.go > hl_log
```
I encountered a series of errors like this:
`start.go:33:2: cannot find package "github.com/hyperledger/fabric/core" in any of:
        /usr/local/opt/go/libexec/src/github.com/hyperledger/fabric/core (from $GOROOT)
        /Users/starry/go-workspace/src/github.com/hyperledger/fabric/core (from $GOPATH)`

**Comment by dloghin** [comment]
@starrycheng - Please get the latest code (commit f4563c4) and use the `start-root.sh` script from there. From your logs, I see you have this line `cd $HL_SOURCE/peer node start > hl_log` which is not valid because `$HL_SOURCE/peer` is a file, not a folder.

**Comment by omsingh1** [comment]
Hi, I want to setup on single PC .. it is totally new for me ..  from where to start .. dont know ..is there any manual (step by step) ?


Is it possible on Ubuntu 16.04 VM ?

Do I have to install additional packages or dependencies?

After cloning the package ..What should be my next step ?

Anyone who  already did the hyperledger setup on single VM with peers plz help.

**Comment by keruisiya** [comment]
> @omsingh1 - Hi, yes, it's possible to setup on a single Ubuntu 16.04 VM.
> 
> 1. install docker (we recommend Docker CE - see here https://docs.docker.com/install/linux/docker-ce/ubuntu/)
> 2. clone this repo, go to `benchmark/hyperledger` and inspect the scripts, read the readme
> 3. inspect `env.sh` and change the variables according to your needs. By default, HL_HOME is set to  benchmark/hyperledger and HL_DATA to benchmark/hyperledger/data
> 4. inspect `hosts` and `clients`. By default, their are set to `localhost` (`127.0.0.1`) so you don't need to change them for a single VM setup
> 5. run `./install.sh`. The peer executable should be in `benchmark/hyperledger/data/go/src/github.com/hyperledger/fabric/build/bin`
> 6. run `./start-root.sh`. Check is peer is up with `ps` or `netstat -tlnp`
> 7. now you can try a benchmark. For example, go to `src/micro/cpuheavy/hyperledger` and run:
> 
> ```
> node deploy.js
> node invoke.js 1000000
> ```

**Comment by keruisiya** [comment]
@dloghin - Hi, can you give steps to run Ethereum benchmark on VMs ? from where to start ..  step by step is better.
need to start to ping VMs after creating the machine cluster?
when to deploy smart contracts？
how to use src/macro/kv_store and smallbank?run usage example directly
