### ISSUE TITLE
smallbank.sol source

### ISSUE THREAD

**Issue by mvrmr** [ooibc88/blockbench#4]
Hi there, I am not seeing the solidity contract source in smallbank.sol, rather is having KVstore source in it.

**_ref_**: blockbench/benchmark/contracts/ethereum/smallbank.sol
Would it be possible to update or share source of smallbank.sol please. Thank you

**Comment by bulldosers** [comment]
Ok, I have submitted the latest one.

**Comment by mvrmr** [comment]
Thank you very much for the quick response. Can you please let me know, where can I find it.

**Comment by mvrmr** [comment]
Got it, Thank you very much :-)
