### ISSUE TITLE
Help in running Hyperledger

### ISSUE THREAD

**Issue by sanju19** [ooibc88/blockbench#40]
I am using Ubuntu 16.04 LTS . After making changes in env.sh I run install.sh I am getting the error

Makefile:59: *** "No go in PATH: Check dependencies".  Stop.

I even set GOPATH in .profile

export GOROOT=/opt/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/data/hyperledger/go
export PATH=$PATH:$GOPATH/bin

Can you tell me whether I am setting the path correct or not?

Also my env.sh is as follows:
HL_HOME=/home/user/blockbench/benchmark/hyperledger
HOSTS=$HL_HOME/hosts
CLIENTS=$HL_HOME/clients
HL_DATA=/home/user/data/hyperledger
HL_SOURCE=$HL_DATA/src/github.com/hyperledger/fabric
#LOG_DIR=$HL_HOME/donothing_donothingresults_1
LOG_DIR=$ETH_HOME/yscb
EXE_HOME=/home/user/blockbench/src/macro/kvstore
BENCHMARK=ycsb

**Comment by dloghin** [comment]
@sanju19 - the `install.sh` script downloads and extracts go in `$HL_DATA` folder. I recommend you set `GOPATH=$HL_DATA/go` and `PATH=$PATH:$GOPATH/bin` and set `HL_SOURCE=HL_DATA/go/src/github.com/hyperledger/fabric`

Let me know if it's working now.

**Comment by sanju19** [comment]
Yes, it's working..

Now when I run install.sh It's showing the following error
           https://pastebin.com/SbtQyfYn
Any idea why this error is coming?

The network I am connected to have a proxy. Do you think this error occurs since I am not configuring proxy inside the docker?

**Comment by dloghin** [comment]
@sanju19 -Do you have Internet access from a docker container? For example, try to ping google.com

**Comment by sanju19** [comment]
yes. this is the output for ping 
       https://pastebin.com/cnDcDsyt
So any idea where I am going wrong?

**Comment by dloghin** [comment]
@sanju19 - Maybe you should try again. If it's not working, try `ping archive.ubuntu.com`? Or try to replace it with a mirror (see here https://launchpad.net/ubuntu/+archivemirrors)
