### ISSUE TITLE
Issue with Driver and the chain

### ISSUE THREAD

**Issue by jamievaravara** [ooibc88/blockbench#42]
At what point am I supposed to start the driver? Before or after i run the run-bench.sh 1 1 1?? 

What is the output of run-bench.sh supposed to look at?

It's a bit tiring that the documentation is not complete, and that the env.sh file is not the only file you have to edit before things start to work. Wish this was described in the documentation.

**Comment by jamievaravara** [comment]
Any help please?

**Comment by dloghin** [comment]
@jamievaravara - Please get the latest code (commit f4563c49def905d6fadba9c031a6baf2187db6fe). I have updated the scripts in `benchmark/hyperledger`. You can execute `./run-bench.sh 1 1 2 100` which should output something like:

```
$ ./run-bench.sh 1 1 2 100
Stopping nodes and clients...
java: no process found
driver: no process found
driver: no process found
peer: no process found
java: no process found
Starting nodes (1) ...
hl_consensus_1.yaml                                                                                                                                                       100% 2788     8.8MB/s   00:00   
bpeer = 127.0.0.1
Waiting for PID 32290 ...
Starting multi-clients (2) ...
127.0.0.1 index 0
IN START_CLIENTS 1 0 1 100
Stopping nodes and clients...
java: no process found
driver: no process found
driver: no process found
peer: no process found
java: no process found
```
You can also check peer's output in `logs/hl_log_root_localhost`

**Comment by keruisiya** [comment]
> At what point am I supposed to start the driver? Before or after i run the run-bench.sh 1 1 1??
> 
> What is the output of run-bench.sh supposed to look at?
> 
> It's a bit tiring that the documentation is not complete, and that the env.sh file is not the only file you have to edit before things start to work. Wish this was described in the documentation.

hi   do you know whether to start the driver first or run the run-bench.sh ?
