### ISSUE TITLE
Option to lock UV scaling?

### ISSUE THREAD

**Issue by Nianor** [ooibc88/blockbench#45]
Hey, I had a random request. Any chance we could get a "lock UV mapping scale" option? Something that would force all the UV mapped components to use a section of texture relative to the size of their actual faces? And you would rescale things globally instead of part by part? It would make it a lot harder to wind up with accidental texture scaling issues.
Basically, there would be a variable S, and if a cube is 1 by 2 by three, each face in the UV mapping is 1*S x 1*s, 1*S x 2*S, so on and so forth. This would be a fixed ratio for all faces, with config options to turn it on or off and change S.
This is a request rather than a bug, but I was told to post it here.

**Comment by keruisiya** [comment]
![image](https://user-images.githubusercontent.com/45038383/48667891-de3d3e00-eb1b-11e8-94a7-43d4030dd7f7.png)
