### ISSUE TITLE
Symbol lookup error after building the kvstore driver

### ISSUE THREAD

**Issue by netanyahuyasser** [ooibc88/blockbench#58]
After installing the restclient-cpp and libcurl, I was able to build the kvstore driver module. However, when running the kvstore micro-benchmark for hyperledger, I got this error:

```bash
 ./driver: symbol lookup error: ./driver: undefined symbol: _ZN10RestClient3getERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

How can I resolve this? Because I thought I already install the restclient-cpp and the libcurl correctly. Otherwise, I would fail to build the driver.

Some similar issues:
1. [Error when making Kvstore driver](https://github.com/ooibc88/blockbench/issues/29)
2. [How to build ./driver binary](https://github.com/ooibc88/blockbench/issues/34)

**Comment by RUAN0007** [comment]
Hi, 

It shoud be due to the dynamic link issue. 
OS fails to find the restclient-cpp library.
If you have installed restclient-cpp, use bash cmd 
`sudo ldconfig` to update the search path for the library.

**Comment by netanyahuyasser** [comment]
@RUAN0007 you deserve a medal. Thanks for the quick reply.
