### ISSUE TITLE
Client Driver polls block in Hyperledger is alway 0

### ISSUE THREAD

**Issue by yingjianwu199868** [ooibc88/blockbench#60]
Hi,

Our team is trying to use blockbench to test  Hyperledger.

However, as we run the test, the client logs always outputs that 
polled block is always 0 tx.
<img width="629" alt="Screen Shot 2019-04-27 at 9 32 22 PM" src="https://user-images.githubusercontent.com/35884103/56856939-0c794200-6934-11e9-8657-4f422207a5e4.png">

We also try to look into the peers (Hyperledger) logs, and it is processing correctly by outputing: 
0m Successfully submitted invoke transaction with different txid ...

Can anyone help us?
Best,
Steven

**Comment by haochenpan** [comment]
HI Steven,

Could you go to Blockbench/Benchmark/Hyperledger folder and check the file permission?

Try do: `sudo chmod o+rw data/`
if there is a permission issue 

Best,
Roger

**Comment by SpicyGoose** [comment]
Did you solve it? I faced the same problem. Please PM me, I really need bits of help.

**Comment by yingjianwu199868** [comment]
Oh! Actually, when I type in ls -l, I find out that the owner of the data folder is root instead of my instance name.

Thank you for your help.

Best,
Steven Wu

**Comment by haochenpan** [comment]
You are welcome.

Best, 
Roger
