### ISSUE TITLE
Running Ethereum with Blockbench

### ISSUE THREAD

**Issue by farazg** [ooibc88/blockbench#7]
Hi, I keep getting node refused whenever I try to start run-bench.sh. What's going on?

**Comment by ug93tad** [comment]
that means you cannot connect to that node. Does that node (IP address) exist? Does it run the client or the server?

**Comment by ug93tad** [comment]
do you have ssh server running on your localhost?

**Comment by farazg** [comment]
what do you mean?

**Comment by farazg** [comment]
???

**Comment by farazg** [comment]
I have ssh but it does not connect to the ip addresses. Hello?

**Comment by farazg** [comment]
Finally got back to this. I removed password authentication and public key authentication from my ssh and I still can not connect to the ip address. 

What I am doing is to run the smallbank driver in one terminal, and then run the "run-bench.sh 1 1 10" command in another terminal.

**Comment by farazg** [comment]
And when I run the driver, i get this result

./driver -db ethereum -ops 10000 -threads 4 -txrate 10 -fp stat.txt -endpoint 127.0.0.1:8000
from address: Failed to query.
to address: Failed to query.
Current TIP = 250
In the last 2s, tx count = 0 latency = 0 outstanding request = 1
In the last 2s, tx count = 0 latency = 0 outstanding request = 1

**Comment by farazg** [comment]
????

**Comment by ug93tad** [comment]
worry, unable to reproduce your errors. 
perhaps you can try running on several physical servers instead of VMs.
