### ISSUE TITLE
How do I setup Blockbench for Hyperledger since 1.0.0 with kafka? 

### ISSUE THREAD

**Issue by ArnChe** [ooibc88/blockbench#9]
Hi, since you are using Hyperledger 0.6. with pbft I want to try to run a benchmark on other HL versions with kafka. I made some changes to env.sh, some start shells. After ./run-bench.sh I get this output and no data as outcome. Have you already made a benchmark with kafka?

peer: no process found
java: no process found
driver: no process found
peer: no process found
java: no process found
driver: no process found
driver: no process found
peer: no process found
java: no process found
driver: no process found
peer: no process found
java: no process found
hl_consensus_2.yaml                                                                   100% 2788     2.7KB/s   00:00
hl_consensus_2.yaml                                                                   100% 2788     2.7KB/s   00:00
bpeer = 192.168.0.50
192.168.0.48 index 0
IN START_CLIENTS 4 0 2 10
peer: no process found
java: no process found
driver: no process found
peer: no process found
java: no process found
driver: no process found
driver: no process found
peer: no process found
java: no process found
driver: no process found
peer: no process found
java: no process found

**Comment by ug93tad** [comment]
We are still working on Hyperledger v1.0 support, but there's no timeline yet. 

We welcome any contributions.
