### ISSUE TITLE
What shall I do after I change configtx.yaml（Fabric v1.4）

### ISSUE THREAD

**Issue by 41889732** [ooibc88/blockbench#91]
After changing batch timout in configtx.yaml, I deleted channel_artifacts and crypto_config, then I ran ./init.sh to generate new file. I didn't get error in setup and deploy step, but when I run ./driver  -db fabric-v1.4 -ops 1000 -threads 4 -txrate 100 -fp stat.txt -endpoint localhost:7041,localhost:7051 
I got some error:
Make sure to call deploy.sh manually at the server side.
Get tip block number fails with err msg Cannot read property \Current TIP = -1
Get tip block number fails with err msg Cannot read property \In the last 2s, tx count = 0 latency = 0 outstanding request = 0
Get tip block number fails with err msg Cannot read property \In the last 2s, tx count = 0 latency = 0 outstanding request = 0
Get tip block number fails with err msg Cannot read property \In the last 2s, tx count = 0 latency = 0 outstanding request = 0
 I can get correct result when I using default files, so I wonder whether I missed some operation after running ./init.sh, I would appreciate it if anyone could help me.

**Comment by RUAN0007** [comment]
Hi, Thank you for your reachout. Note that in our deployment of Fabric 1.4, the blockbench cpp client delegates the bock pulling request to [poll_blk.js](blockbench/src/macro/kvstore/fabric-v1.4-node/poll_blk.js), which in turn requires to initiate the network in [ccutil.js](blockbench/src/macro/kvstore/fabric-v1.4-node/ccutil.js). As you can see,  [ccutil.js](blockbench/src/macro/kvstore/fabric-v1.4-node/ccutil.js) has some hardcoded path, such as __keyPath__, etc. Pls update them accordingly in your own setup. You can directly invoke `poll_blk.js` to test whether the script function properly.

**Comment by 41889732** [comment]
> Hi, Thank you for your reachout. Note that in our deployment of Fabric 1.4, the blockbench cpp client delegates the bock pulling request to [poll_blk.js](https://github.com/ooibc88/blockbench/blob/master/src/macro/kvstore/fabric-v1.4-node/poll_blk.js), which in turn requires to initiate the network in [ccutil.js](https://github.com/ooibc88/blockbench/blob/master/src/macro/kvstore/fabric-v1.4-node/ccutil.js). As you can see, [ccutil.js](https://github.com/ooibc88/blockbench/blob/master/src/macro/kvstore/fabric-v1.4-node/ccutil.js) has some hardcoded path, such as **keyPath**, etc. Pls update them accordingly in your own setup. You can directly invoke `poll_blk.js` to test whether the script function properly.

I can run properly after updating keyPath, thank you very much!
