### ISSUE TITLE
How to adjust parameters in benchmark？

### ISSUE THREAD

**Issue by 41889732** [ooibc88/blockbench#92]
Hello, When I tried to reproduce the experiment in the fabricsharp paper with default parameters, I got very low throughtput, so I wanted to modify some parameters to be consistent with the experiment in paper, but I only found a way to modify the blocksize, and I don't know how to modify other order parameters and client parameters(such as  hot account, Write hot ratio, Client delay, Read interval). So I want to know how to modify them. My Fabric version is v1.4.
Thank you very much.

**Comment by RUAN0007** [comment]
Hi, when we are doing SIGMOD21 paper, we haven't added Fabric 1.4 support to BlockBench. Instead, we use a fork version of Caliper and we open source it as well. You can refer to this [link](https://github.com/RUAN0007/caliper-min/tree/master/benchmark/custom), which shows an experiment demo on a single machine. But to exactly reproduce experiments, you have to deploy both the FabricSharp and Caliper distributedly.

**Comment by 41889732** [comment]
I will try to use caliper, Thanks a lot!
